Return-Path: <linux-doc-owner@vger.kernel.org>
X-Original-To: lists+linux-doc@lfdr.de
Delivered-To: lists+linux-doc@lfdr.de
Received: from vger.kernel.org (vger.kernel.org [23.128.96.18])
	by mail.lfdr.de (Postfix) with ESMTP id DD293206D54
	for <lists+linux-doc@lfdr.de>; Wed, 24 Jun 2020 09:11:29 +0200 (CEST)
Received: (majordomo@vger.kernel.org) by vger.kernel.org via listexpand
        id S2389588AbgFXHL0 (ORCPT <rfc822;lists+linux-doc@lfdr.de>);
        Wed, 24 Jun 2020 03:11:26 -0400
Received: from lindbergh.monkeyblade.net ([23.128.96.19]:39556 "EHLO
        lindbergh.monkeyblade.net" rhost-flags-OK-OK-OK-OK) by vger.kernel.org
        with ESMTP id S2387849AbgFXHLX (ORCPT
        <rfc822;linux-doc@vger.kernel.org>); Wed, 24 Jun 2020 03:11:23 -0400
Received: from mail-pf1-x444.google.com (mail-pf1-x444.google.com [IPv6:2607:f8b0:4864:20::444])
        by lindbergh.monkeyblade.net (Postfix) with ESMTPS id C5CFDC061755
        for <linux-doc@vger.kernel.org>; Wed, 24 Jun 2020 00:11:23 -0700 (PDT)
Received: by mail-pf1-x444.google.com with SMTP id f9so759456pfn.0
        for <linux-doc@vger.kernel.org>; Wed, 24 Jun 2020 00:11:23 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=chromium.org; s=google;
        h=date:from:to:cc:subject:message-id:references:mime-version
         :content-disposition:in-reply-to;
        bh=IaIupdZDTPQkymgBfVG+0UDzO2HZVyEhIFNy78lMOE8=;
        b=jpmMG0PHfYi6EnAmdG5fjMx0DjviB4vfHp7oxw+UsZCuKGtKIGPQi/axyb5qwcz/QA
         ZauxRm4oA32Nn3tJIT1A1IknQybBPHIEaqBWXeV6EZXzFaFNG1rzC+DdW/cpf5FoYqst
         OuHNnTxKdxtEFHNy0ON5sPTSLlYJ7o0Bln868=
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=x-gm-message-state:date:from:to:cc:subject:message-id:references
         :mime-version:content-disposition:in-reply-to;
        bh=IaIupdZDTPQkymgBfVG+0UDzO2HZVyEhIFNy78lMOE8=;
        b=WnaDqU4CNVU3FAOAnHNBdR2NRXPrUpzJqJaM32veBiRP+3JwVLqvqyVVPyWfmxAegT
         AsO/zbKWUY+0qa++32dEqe2kCllONKgAdlPM6CTiKiOI3y7UHualasdCmHudacLXFtVp
         I96wbsYlKZ8GamEoUfUDgGcZIfGht+spmvnqmRuNvdSmkgOmDafjGphPHSNT2g94hG4O
         m5rdw/0grmgXfq2kWCnTe/R7ry0SNIQMk+AwKLiNroiy83676xUFvr9Kue9B973xsbwd
         znmmBQOAtVjbvlKdtsdZeR7bIgOss/oV5B/E4WZSEYhFf0VfEnpQUUublKVmXkmidY6p
         ORDw==
X-Gm-Message-State: AOAM530/EAgo2bxO9zJWHlOMMhPhGhDO6THdZtsp2ULcKu0/q9FT1UcE
        sogtSniAaVSd98hcaFAO1GeLLA==
X-Google-Smtp-Source: ABdhPJzQdr21ClhxdwWwshImYU97Su78pVPktGGTYd8dh+NTMu+2Fty5hs3KNmkDqlNAUGQYwOx7jw==
X-Received: by 2002:a63:ac53:: with SMTP id z19mr19935654pgn.181.1592982683374;
        Wed, 24 Jun 2020 00:11:23 -0700 (PDT)
Received: from www.outflux.net (smtp.outflux.net. [198.145.64.163])
        by smtp.gmail.com with ESMTPSA id g9sm18897717pfm.151.2020.06.24.00.11.21
        (version=TLS1_3 cipher=TLS_AES_256_GCM_SHA384 bits=256/256);
        Wed, 24 Jun 2020 00:11:22 -0700 (PDT)
Date:   Wed, 24 Jun 2020 00:11:21 -0700
From:   Kees Cook <keescook@chromium.org>
To:     Kristen Carlson Accardi <kristen@linux.intel.com>
Cc:     tglx@linutronix.de, mingo@redhat.com, bp@alien8.de,
        Jonathan Corbet <corbet@lwn.net>, x86@kernel.org,
        "H. Peter Anvin" <hpa@zytor.com>, arjan@linux.intel.com,
        linux-kernel@vger.kernel.org, kernel-hardening@lists.openwall.com,
        rick.p.edgecombe@intel.com, Tony Luck <tony.luck@intel.com>,
        linux-doc@vger.kernel.org
Subject: Re: [PATCH v3 08/10] x86: Add support for function granular KASLR
Message-ID: <202006240007.095694C@keescook>
References: <20200623172327.5701-1-kristen@linux.intel.com>
 <20200623172327.5701-9-kristen@linux.intel.com>
MIME-Version: 1.0
Content-Type: text/plain; charset=us-ascii
Content-Disposition: inline
In-Reply-To: <20200623172327.5701-9-kristen@linux.intel.com>
Sender: linux-doc-owner@vger.kernel.org
Precedence: bulk
List-ID: <linux-doc.vger.kernel.org>
X-Mailing-List: linux-doc@vger.kernel.org

On Tue, Jun 23, 2020 at 10:23:25AM -0700, Kristen Carlson Accardi wrote:
> This commit contains the changes required to re-layout the kernel text
> sections generated by -ffunction-sections shortly after decompression.
> Documentation of the feature is also added.
> [...]
> Signed-off-by: Kristen Carlson Accardi <kristen@linux.intel.com>
> Reviewed-by: Tony Luck <tony.luck@intel.com>
> Tested-by: Tony Luck <tony.luck@intel.com>

This looks good! I wonder about some way (in the future) to share the
sorting routines for kallsyms, exceptions, orc, etc. For now, though, I
think this is fine.

> [...]
> +	if (cmdline_find_option("fgkaslr", arg, sizeof(arg)) == 3 &&
> +	    !strncmp(arg, "off", 3)) {
> +		warn("FG_KASLR disabled on cmdline.");
> +		nofgkaslr = 1;
> +	}

I was recently reminded by Randy Lunlap to document my new boot params,
so I need to point out the same here. :) With a section added to
Documentation/admin-guide/kernel-parameters.txt
consider this:

Reviewed-by: Kees Cook <keescook@chromium.org>

-- 
Kees Cook
